# Generated by Django 4.2.26 on 2025-11-21 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
